-- MySQL Script generated by MySQL Workbench
-- Tue Jan 27 13:11:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema school_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_management_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `school_management_system` ;

-- -----------------------------------------------------
-- Table `school_management_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role` ENUM('admin', 'teacher', 'student', 'parent') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`activation_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`activation_tokens` (
  `token` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_used` TINYINT(1) NULL DEFAULT '0',
  `used_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`token`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `activation_tokens_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`announcements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `posted_by` INT NOT NULL,
  `posted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `posted_by` (`posted_by` ASC) VISIBLE,
  CONSTRAINT `announcements_ibfk_1`
    FOREIGN KEY (`posted_by`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grade` VARCHAR(50) NOT NULL,
  `section` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `grade` (`grade` ASC, `section` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `subject_name` (`subject_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`assignments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `due_date` DATETIME NOT NULL,
  `assignment_file_url` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Server file path for assignment document',
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `class_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  INDEX `fk_assignments_class` (`class_id` ASC) VISIBLE,
  INDEX `fk_assignments_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `assignments_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_assignments_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `school_management_system`.`classes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_assignments_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_management_system`.`subjects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `roll_number` VARCHAR(20) NULL DEFAULT NULL,
  `class_id` INT NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `parent_id` (`parent_id` ASC) VISIBLE,
  INDEX `class_id` (`class_id` ASC) VISIBLE,
  CONSTRAINT `students_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `students_ibfk_2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `students_ibfk_3`
    FOREIGN KEY (`class_id`)
    REFERENCES `school_management_system`.`classes` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`assignment_submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`assignment_submissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assignment_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `submission_file_url` VARCHAR(255) NOT NULL,
  `submitted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `assignment_id` (`assignment_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `assignment_submissions_ibfk_1`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `school_management_system`.`assignments` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `assignment_submissions_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`assignment_marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`assignment_marks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assignment_submission_id` INT NOT NULL,
  `marks` DECIMAL(5,2) NOT NULL,
  `feedback` TEXT NULL DEFAULT NULL,
  `reviewed_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `assignment_submission_id` (`assignment_submission_id` ASC) VISIBLE,
  CONSTRAINT `assignment_marks_ibfk_1`
    FOREIGN KEY (`assignment_submission_id`)
    REFERENCES `school_management_system`.`assignment_submissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`timetable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NOT NULL,
  `day_of_week` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday') NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `teacher_id` INT NOT NULL,
  `subject_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_id` (`class_id` ASC) VISIBLE,
  INDEX `teacher_id` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_timetable_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_timetable_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_management_system`.`subjects` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `timetable_ibfk_1`
    FOREIGN KEY (`class_id`)
    REFERENCES `school_management_system`.`classes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `timetable_ibfk_2`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `status` ENUM('present', 'absent', 'late') NOT NULL,
  `date` DATE NOT NULL,
  `timetable_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `fk_attendance_timetable` (`timetable_id` ASC) VISIBLE,
  CONSTRAINT `attendance_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_attendance_timetable`
    FOREIGN KEY (`timetable_id`)
    REFERENCES `school_management_system`.`timetable` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`certificate_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`certificate_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`certificate_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`certificate_issue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `issue_date` DATE NOT NULL,
  `certificate_number` VARCHAR(50) NOT NULL,
  `issued_by` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `certificate_type_id` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `certificate_number` (`certificate_number` ASC) VISIBLE,
  INDEX `idx_student_id` (`student_id` ASC) VISIBLE,
  INDEX `idx_issue_date` (`issue_date` ASC) VISIBLE,
  INDEX `issued_by` (`issued_by` ASC) VISIBLE,
  INDEX `fk_cert_type` (`certificate_type_id` ASC) VISIBLE,
  CONSTRAINT `certificate_issue_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `certificate_issue_ibfk_2`
    FOREIGN KEY (`issued_by`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_cert_type`
    FOREIGN KEY (`certificate_type_id`)
    REFERENCES `school_management_system`.`certificate_types` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `event_date` DATE NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by` (`created_by` ASC) VISIBLE,
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`created_by`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`exams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `exam_date` DATE NOT NULL,
  `duration` INT NOT NULL,
  `status` ENUM('draft', 'published', 'archived') NULL DEFAULT 'draft',
  `teacher_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `class_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `total_marks` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_exams_class` (`class_id` ASC) VISIBLE,
  INDEX `fk_exams_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_exams_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `school_management_system`.`classes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_exams_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_management_system`.`subjects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`question_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`question_bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_text` TEXT NOT NULL,
  `question_type` ENUM('multiple_choice', 'true_false', 'short_answer', 'essay') NOT NULL,
  `topic` VARCHAR(150) NULL DEFAULT NULL,
  `difficulty_level` ENUM('easy', 'medium', 'hard') NULL DEFAULT 'medium',
  `marks` INT NOT NULL DEFAULT '1',
  `options` TEXT NULL DEFAULT NULL COMMENT 'JSON string for MCQ options',
  `correct_answer` TEXT NULL DEFAULT NULL,
  `teacher_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `subject_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_teacher` (`teacher_id` ASC) VISIBLE,
  INDEX `idx_difficulty` (`difficulty_level` ASC) VISIBLE,
  INDEX `idx_type` (`question_type` ASC) VISIBLE,
  INDEX `fk_question_bank_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_bank_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_management_system`.`subjects` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `question_bank_ibfk_1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`exam_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`exam_questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exam_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `marks` INT NOT NULL COMMENT 'Marks for this question in this exam',
  `question_order` INT NOT NULL COMMENT 'Order of question in exam',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_exam_question` (`exam_id` ASC, `question_id` ASC) VISIBLE,
  INDEX `idx_exam` (`exam_id` ASC) VISIBLE,
  INDEX `idx_question` (`question_id` ASC) VISIBLE,
  CONSTRAINT `exam_questions_ibfk_1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `school_management_system`.`exams` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `exam_questions_ibfk_2`
    FOREIGN KEY (`question_id`)
    REFERENCES `school_management_system`.`question_bank` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `type` ENUM('ptm', 'system', 'assignment', 'exam') NOT NULL DEFAULT 'system',
  `is_read` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_notifications_user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_notifications_is_read` (`is_read` ASC) VISIBLE,
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`parents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `parents_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`password_resets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_used` TINYINT(1) NULL DEFAULT '0',
  `used_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token` (`token` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `password_resets_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `subject_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_teacher_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_management_system`.`subjects` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `teachers_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`portfolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`portfolios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `teacher_id` INT NULL DEFAULT NULL,
  `performance_summary` TEXT NULL DEFAULT NULL,
  `activities_achievements` TEXT NULL DEFAULT NULL,
  `areas_improvement` TEXT NULL DEFAULT NULL,
  `discipline_remarks` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `fk_portfolios_teacher_final` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_portfolios_teacher_final`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_management_system`.`teachers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`ptm_meetings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`ptm_meetings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `parent_id` INT NOT NULL,
  `meeting_date` DATE NOT NULL,
  `meeting_time` VARCHAR(20) NOT NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'completed', 'reschedule_requested') NOT NULL DEFAULT 'pending',
  `initiator` ENUM('parent', 'teacher') NOT NULL DEFAULT 'parent',
  `notes` TEXT NULL DEFAULT NULL,
  `rejection_reason` TEXT NULL DEFAULT NULL,
  `alternative_date` DATE NULL DEFAULT NULL,
  `alternative_time` VARCHAR(20) NULL DEFAULT NULL,
  `teacher_remarks` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `teacher_id` (`teacher_id` ASC) VISIBLE,
  INDEX `parent_id` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `ptm_meetings_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `ptm_meetings_ibfk_2`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `ptm_meetings_ibfk_3`
    FOREIGN KEY (`parent_id`)
    REFERENCES `school_management_system`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`ptm_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`ptm_feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ptm_meeting_id` INT NOT NULL,
  `feedback_from` ENUM('teacher', 'parent') NOT NULL,
  `feedback` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ptm_meeting_id` (`ptm_meeting_id` ASC) VISIBLE,
  CONSTRAINT `ptm_feedback_ibfk_1`
    FOREIGN KEY (`ptm_meeting_id`)
    REFERENCES `school_management_system`.`ptm_meetings` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`student_exam_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`student_exam_attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `exam_id` INT NOT NULL,
  `start_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NULL DEFAULT NULL,
  `status` ENUM('in_progress', 'submitted', 'evaluated') NULL DEFAULT 'in_progress',
  PRIMARY KEY (`id`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `exam_id` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `student_exam_attempts_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `student_exam_attempts_ibfk_2`
    FOREIGN KEY (`exam_id`)
    REFERENCES `school_management_system`.`exams` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`student_exam_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`student_exam_answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attempt_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `selected_option` VARCHAR(255) NULL DEFAULT NULL,
  `text_answer` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `attempt_id` (`attempt_id` ASC) VISIBLE,
  INDEX `question_id` (`question_id` ASC) VISIBLE,
  CONSTRAINT `student_exam_answers_ibfk_1`
    FOREIGN KEY (`attempt_id`)
    REFERENCES `school_management_system`.`student_exam_attempts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `student_exam_answers_ibfk_2`
    FOREIGN KEY (`question_id`)
    REFERENCES `school_management_system`.`question_bank` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`student_todos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`student_todos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `priority` ENUM('high', 'medium', 'low') NULL DEFAULT 'medium',
  `status` ENUM('pending', 'in_progress', 'completed') NULL DEFAULT 'pending',
  `category` VARCHAR(50) NULL DEFAULT 'general',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `completed_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_student_id` (`student_id` ASC) VISIBLE,
  INDEX `idx_status` (`status` ASC) VISIBLE,
  INDEX `idx_due_date` (`due_date` ASC) VISIBLE,
  CONSTRAINT `student_todos_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `school_management_system`.`term_marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_management_system`.`term_marks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `term` VARCHAR(50) NOT NULL,
  `marks` DECIMAL(5,2) NOT NULL,
  `feedback` TEXT NULL DEFAULT NULL,
  `entered_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `subject_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `fk_term_marks_subject` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_term_marks_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_management_system`.`subjects` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `term_marks_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_management_system`.`students` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
